Rama Gale
AMB2208

In [ ]:
import pandas as pd
prod=pd.Series([30,60,45,25],index=["wheat","rice",'maize','barley'])

print(prod)

wheat     30
rice      60
maize     45
barley    25
dtype: int64

In [ ]:
#by crp label
print(prod["rice"])
print(prod.loc["rice"])

60
60

In [ ]:
#by production
print(prod.iloc[0])
print(prod.iloc[3])

30
25

In [ ]:
print(prod.sum())
print(prod.mean())
print(prod.idxmax())#it print  the index label of the maximum value in the series
print(prod.max())

160
40.0
rice
60

In [ ]:
#inceased data sture
in_prod=prod* 1.10
print(in_prod)

wheat     33.0
rice      66.0
maize     49.5
barley    27.5
dtype: float64

In [ ]:
highprod =prod[prod>40]
print(highprod)
print()
print(prod>40)

rice     60
maize    45
dtype: int64

wheat     False
rice       True
maize      True
barley    False
dtype: bool

In [ ]:
import pandas as pd
df=pd.DataFrame({
    'name':["akhil", 'bobby','charan'],
    'age':[25,30,35],
    'city':['delhi','mumbai','goa']
},index=['a','b','c'] )
print(df)
print()
print(df.loc['c'])

     name  age    city
a   akhil   25   delhi
b   bobby   30  mumbai
c  charan   35     goa

name    charan
age         35
city       goa
Name: c, dtype: object

In [ ]:
print(df)
print()
print(df.loc[['a','c','b'],['name','city']])

     name  age    city
a   akhil   25   delhi
b   bobby   30  mumbai
c  charan   35     goa

     name    city
a   akhil   delhi
c  charan     goa
b   bobby  mumbai

In [ ]:
print(df.loc["a":"b"])

    name  age    city
a  akhil   25   delhi
b  bobby   30  mumbai

In [ ]:
print(df.loc[df["age"]>28,["name","age"]])

     name  age
b   bobby   30
c  charan   35

In [ ]:
print(df.iloc[[0,1,2]])

     name  age    city
a   akhil   25   delhi
b   bobby   30  mumbai
c  charan   35     goa

In [ ]:
print(df.iloc[[0,2],[1,2]]) #select rows and column by position

   age   city
a   25  delhi
c   35    goa

In [ ]:
print(df.iloc[[0,1],[1,2]]) #select rows and column by position

   age    city
a   25   delhi
b   30  mumbai

In [ ]:
print(df.iloc[[0,1,2],[1,2]]) #select rows and column by position

   age    city
a   25   delhi
b   30  mumbai
c   35     goa

In [ ]:
print(df.iloc[[0,2],[0,1,2]]) #select rows and column by position

     name  age   city
a   akhil   25  delhi
c  charan   35    goa

In [ ]:
import pandas as pd
data={
    "farm":["farm a","farm b","farm c","farm d"],
    "Crop":["wheat","rice","wheat","maizze"],
    "areahect":[10,15,8,12],
    "prodtons":[30,60,24,36]
}
df=pd.DataFrame(data)
print(df)

     farm    Crop  areahect  prodtons
0  farm a   wheat        10        30
1  farm b    rice        15        60
2  farm c   wheat         8        24
3  farm d  maizze        12        36

In [ ]:
df.head(2)

     farm   Crop  areahect  prodtons
0  farm a  wheat        10        30
1  farm b   rice        15        60

In [ ]:
df.head()#first few rows

     farm    Crop  areahect  prodtons
0  farm a   wheat        10        30
1  farm b    rice        15        60
2  farm c   wheat         8        24
3  farm d  maizze        12        36

In [ ]:
df.tail(3)

     farm    Crop  areahect  prodtons
1  farm b    rice        15        60
2  farm c   wheat         8        24
3  farm d  maizze        12        36

In [ ]:
df.info()# basic information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   farm      4 non-null      object
 1   Crop      4 non-null      object
 2   areahect  4 non-null      int64
 3   prodtons  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
df.describe()#summary statistic

        areahect   prodtons
count   4.000000   4.000000
mean   11.250000  37.500000
std     2.986079  15.779734
min     8.000000  24.000000
25%     9.500000  28.500000
50%    11.000000  33.000000
75%    12.750000  42.000000
max    15.000000  60.000000

In [ ]:
df["yield_tos_hec"]=df["prodtons"]/df["areahect"]
print(df)

     farm    Crop  areahect  prodtons  yield_tos_hec
0  farm a   wheat        10        30            3.0
1  farm b    rice        15        60            4.0
2  farm c   wheat         8        24            3.0
3  farm d  maizze        12        36            3.0

In [ ]:
print(df.iloc[[1,3]])

     farm    Crop  areahect  prodtons  yield_tos_hec
1  farm b    rice        15        60            4.0
3  farm d  maizze        12        36            3.0

In [ ]:
print(df.iloc[[0,1,2,3],[0,1,2]])

     farm    Crop  areahect
0  farm a   wheat        10
1  farm b    rice        15
2  farm c   wheat         8
3  farm d  maizze        12

In [ ]:
print(df.loc[[0,1,2,],["farm","Crop","areahect"]])

     farm   Crop  areahect
0  farm a  wheat        10
1  farm b   rice        15
2  farm c  wheat         8

In [ ]:
print(df.iloc[[0,1,2,3],[0,1,2]])

     farm    Crop  areahect
0  farm a   wheat        10
1  farm b    rice        15
2  farm c   wheat         8
3  farm d  maizze        12

In [ ]:
#filter data
#farm growing wheat
print(df["Crop"]=="wheat")
print()
wheat_farm=df[df["Crop"]=="wheat"]
print(wheat_farm)

0     True
1    False
2     True
3    False
Name: Crop, dtype: bool

     farm   Crop  areahect  prodtons  yield_tos_hec
0  farm a  wheat        10        30            3.0
2  farm c  wheat         8        24            3.0

In [ ]:
#farms with yeld geater than 3
high_yield=df[df["yield_tos_hec"]>3]
print(high_yield)

     farm  Crop  areahect  prodtons  yield_tos_hec
1  farm b  rice        15        60            4.0

In [ ]:
#sort farm by highest production
sorted_df=df.sort_values(by="prodtons",ascending=False)
print(sorted_df)

     farm    Crop  areahect  prodtons  yield_tos_hec
1  farm b    rice        15        60            4.0
3  farm d  maizze        12        36            3.0
0  farm a   wheat        10        30            3.0
2  farm c   wheat         8        24            3.0

In [ ]:
#group; by operation
avg_yield=df.groupby("Crop")["yield_tos_hec"].sum()
print(avg_yield)

Crop
maizze    3.0
rice      4.0
wheat     6.0
Name: yield_tos_hec, dtype: float64

In [ ]:
#group; by operation
avg_yield=df.groupby("Crop")["yield_tos_hec"].mean()
print(avg_yield)

Crop
maizze    3.0
rice      4.0
wheat     3.0
Name: yield_tos_hec, dtype: float64

In [ ]:
import pandas as pd
import numpy as np

#create data with missing values
data=pd.DataFrame({
    "plot":["A","B","C","D","E"],
    "yields_kg": [2500,np.nan,2800,np.nan,2600],
    "rainfall": [150,200,np.nan,180,170],
    "tempaerature":[28,30,29,np.nan,27]
})
print()
print("===data with missing values===")
print(data)
#detecting missing data
print()
print("===detecting missing data===")
print("is null?")
print(data.isnull())
print()
print(f"total missing per coloumn:")
print(data.isnull().sum())

===data with missing values===
  plot  yields_kg  rainfall  tempaerature
0    A     2500.0     150.0          28.0
1    B        NaN     200.0          30.0
2    C     2800.0       NaN          29.0
3    D        NaN     180.0           NaN
4    E     2600.0     170.0          27.0

===detecting missing data===
is null?
    plot  yields_kg  rainfall  tempaerature
0  False      False     False         False
1  False       True     False         False
2  False      False      True         False
3  False       True     False          True
4  False      False     False         False

total missing per coloumn:
plot            0
yields_kg       2
rainfall        1
tempaerature    1
dtype: int64

In [ ]:
# filling missing values
print("filling strategies")
print()
# fill with mean
data_mean=data.copy()
print(data_mean["yields_kg"])
data_mean["yields_kg"]=data_mean["yields_kg"].fillna(data_mean["yields_kg"].mean())
print("fill with mean")
print(data_mean["yields_kg"])

filling strategies

0    2500.0
1       NaN
2    2800.0
3       NaN
4    2600.0
Name: yields_kg, dtype: float64
fill with mean
0    2500.000000
1    2633.333333
2    2800.000000
3    2633.333333
4    2600.000000
Name: yields_kg, dtype: float64

In [ ]:
#fill with median
data_median=data.copy()
data_median["rainfall"]=data_median["rainfall"].fillna(data_median["rainfall"].median())
print("fill with median")
print(data_median["rainfall"])
#

fill with median
0    150.0
1    200.0
2    175.0
3    180.0
4    170.0
Name: rainfall, dtype: float64

In [ ]:
#forward fill (use previous value)
data_ffill=data.copy()
print(data_ffill)
data_ffill=data_ffill.fillna(method="ffill")
print("forward fill")
print(data_ffill)
#ffill-it replaces missing values(nan)
# with the last valid (non-missing) value above it in the coloumn.

  plot  yields_kg  rainfall  tempaerature
0    A     2500.0     150.0          28.0
1    B        NaN     200.0          30.0
2    C     2800.0       NaN          29.0
3    D        NaN     180.0           NaN
4    E     2600.0     170.0          27.0
forward fill
  plot  yields_kg  rainfall  tempaerature
0    A     2500.0     150.0          28.0
1    B     2500.0     200.0          30.0
2    C     2800.0     200.0          29.0
3    D     2800.0     180.0          29.0
4    E     2600.0     170.0          27.0

/tmp/ipython-input-3178736952.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_ffill=data_ffill.fillna(method="ffill")

In [ ]:
# dropping missing data
print("droping rows")
data_dropped=data.dropna()
print(data_dropped)
print(f"original rows:{len(data)},After drop:{len(data_dropped)}")

droping rows
  plot  yields_kg  rainfall  tempaerature
0    A     2500.0     150.0          28.0
4    E     2600.0     170.0          27.0
original rows:5,After drop:2